CREATE DATABASE BLOG;
USE BLOG;
CREATE TABLE ROLE(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL
);

CREATE TABLE USER_DETAILS(
ID BIGINT  PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(20) NOT NULL,
EMAIL_ID VARCHAR(50) UNIQUE NOT NULL,
ROLE_ID INT DEFAULT 2,
CONSTRAINT FK_ROLE_ID FOREIGN  KEY(ROLE_ID) REFERENCES ROLE(ID)
);

CREATE TABLE ARTICLES(
ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
USER_ID BIGINT ,
TITLE VARCHAR(50) NOT NULL,
CONTENT TEXT NOT NULL,
CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
ACTIVE BOOLEAN DEFAULT 1,
CONSTRAINT FK_USER_ID FOREIGN  KEY(USER_ID) REFERENCES USER_DETAILS(ID),
UNIQUE(USER_ID,TITLE)
);



CREATE TABLE SEED_CATAGORY(
ID BIGINT  PRIMARY KEY AUTO_INCREMENT NOT NULL,
CATAGORY VARCHAR(50) NOT NULL,
USER_ID BIGINT NOT NULL,
CONSTRAINT FK_CATAGORY_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER_DETAILS(ID),
UNIQUE(CATAGORY,USER_ID)
);

CREATE TABLE ARTICLE_CATAGORY(
ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ARTICLE_ID BIGINT UNSIGNED NOT NULL,
CATAGORY_ID BIGINT NOT NULL,
CONSTRAINT FK_ARTICLE_ID FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLES(ID),
CONSTRAINT FK_CATAGORY_ID FOREIGN KEY(CATAGORY_ID) REFERENCES SEED_CATAGORY(ID)
);

CREATE TABLE COMMENTS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ARTICLE_ID BIGINT UNSIGNED NOT NULL,
USER_ID BIGINT NOT NULL,
COMMENTS TEXT NOT NULL,
CONSTRAINT FK_ARTICLES_ID FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLES(ID),
CONSTRAINT FK_USERS_ID FOREIGN KEY(USER_ID) REFERENCES USER_DETAILS(ID)
);

CREATE TABLE RATINGS_GIVEN(
ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
USER_ID BIGINT NOT NULL,
ARTICLE_ID BIGINT UNSIGNED NOT NULL,
RATINGS INT NOT NULL,
LIKES BOOLEAN DEFAULT 0,
CONSTRAINT FK_RAT_ARTICLES_ID FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLES(ID),
CONSTRAINT FK_RAT_USERS_ID FOREIGN KEY(USER_ID) REFERENCES USER_DETAILS(ID),
UNIQUE(USER_ID,ARTICLE_ID)
);